version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: le-budget-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: le_budget
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5